// =========================================================
// lib/conversation-id.js
//
// Backend-generated conversation IDs (UUIDs). Validate before
// any filesystem path join so IDs cannot become path traversal.
// =========================================================


import crypto from "node:crypto";


const CONVERSATION_ID_PATTERN =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;


export function createConversationId() {
    return crypto.randomUUID();
}


export function isValidConversationId(value) {
    return typeof value === "string" && CONVERSATION_ID_PATTERN.test(value);
}


export function assertValidConversationId(value) {
    if (!isValidConversationId(value)) {
        const error = new Error(
            "Conversation id must be a valid UUID generated by the server.",
        );
        error.code = "CONVERSATION_ID_INVALID";
        error.status = 400;
        throw error;
    }

    return value;
}
